# frozen_string_literal: true

module PaypalAPI
  #
  # AccessToken object stores authorization string and its expire time.
  #
  class AccessToken
    attr_reader :requested_at, :expires_at, :authorization_string

    #
    # Initializes AccessToken object
    #
    # @param requested_at [Time] Time when token was requested
    # @param expires_in [Integer] Count of seconds until token expires
    # @param access_token [String] Aceess token string generated by PayPal
    # @param token_type [String] Aceess token type, which is constantly `Bearer`
    #
    # @return [AccessToken] Generated AccessToken object
    #
    def initialize(requested_at:, expires_in:, access_token:, token_type:)
      @requested_at = requested_at
      @expires_at = requested_at + expires_in
      @authorization_string = "#{token_type} #{access_token}"
      freeze
    end

    #
    # Shows if current AccessToken was expired
    #
    def expired?
      Time.now >= expires_at
    end

    #
    # Instance representation string. Default was overwritten to hide original access_token
    #
    def inspect
      "#<#{self.class.name} methods: (requested_at, expires_at, expired?, authorization_string)>"
    end

    alias_method :to_s, :inspect
  end
end
