# frozen_string_literal: true

module PaypalAPI
  #
  # AccessToken object stores authorization string and its expire time.
  #
  # @api private
  #
  class AccessToken
    # Time when access token request was sent
    # @return [Time] Time
    attr_reader :requested_at

    # Time when access token request expires
    # @return [Time] Time
    attr_reader :expires_at

    # Authorization string
    # @return [String] Authorization string
    attr_reader :authorization_string

    #
    # Initializes AccessToken object
    #
    # @param requested_at [Time] Time when token was requested
    # @param expires_in [Integer] Count of seconds until token expires
    # @param access_token [String] Aceess token string generated by PayPal
    # @param token_type [String] Aceess token type, which is constantly `Bearer`
    #
    # @return [AccessToken] Generated AccessToken object
    #
    def initialize(requested_at:, expires_in:, access_token:, token_type:)
      @requested_at = requested_at
      @expires_at = requested_at + expires_in
      @authorization_string = "#{token_type} #{access_token}"
      freeze
    end

    #
    # Shows if current AccessToken was expired
    #
    def expired?
      Time.now >= expires_at
    end

    #
    # Instance representation string
    #
    # @return [String] Inspect value
    #
    def inspect
      "#<#{self.class.name} methods: (requested_at, expires_at, expired?, authorization_string)>"
    end

    alias_method :to_s, :inspect
  end
end
