name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        include:
          - ruby: "head"
            gemfile: "gemfiles/2.6.3.gemfile"
          - ruby: "3.4"
            gemfile: "gemfiles/2.6.3.gemfile"
          - ruby: "3.3"
            gemfile: "gemfiles/2.5.23.gemfile"
          - ruby: "3.2"
            gemfile: "gemfiles/2.5.23.gemfile"
          - ruby: "3.1"
            gemfile: "gemfiles/2.5.23.gemfile"
          - ruby: "3.0"
            gemfile: "gemfiles/2.5.23.gemfile"
          - ruby: "2.7"
            gemfile: "gemfiles/2.4.22.gemfile"
          - ruby: "2.6"
            gemfile: "gemfiles/2.4.22.gemfile"
          - ruby: "jruby-9.4.11"
            gemfile: "gemfiles/2.4.22.gemfile"
          - ruby: "truffleruby-24.1.2"
            gemfile: "Gemfile"

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install codespell
        if: startsWith(matrix.ruby, '3.4')
        run: |
          python -m pip install --upgrade pip
          pip install codespell==2.3.0
      - name: Check spelling with codespell
        if: startsWith(matrix.ruby, '3.4')
        run: codespell --skip="./sig,./doc,./coverage,./vendor" || exit 1

      # We want to run this only on newest stable ruby
      - name: Check Code Standards
        if: startsWith(matrix.ruby, '3.4')
        run: bundle exec rubocop

      # We want to run this only on newest stable ruby
      - name: Markdown linter
        if: startsWith(matrix.ruby, '3.4')
        run: bundle exec mdl README.md CHANGELOG.md RELEASE.md

      # This should be run on all ruby versions
      # (except 3.4, it will be run in nexy command together with coverage)
      - name: Test
        if: ${{ ! startsWith(matrix.ruby, '3.4') }}
        run: bundle exec rspec

      # Coverage is generated only in ruby3.4 as configured in spec/simplecov_helper.rb
      - name: Test & publish code coverage
        if: startsWith(matrix.ruby, '3.4')
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 195b4c2b433a5c635a8e2d84f4b79c95a363d37a9b8706d7a4faa6d4da1ad5e8
        with:
          coverageCommand: bundle exec rspec
